### ISSUE TITLE
So how do I pronounce this name?

### ISSUE THREAD

**Issue by nvkelso** [mapzen/joerd#20]
Baldur to the rescue!

**Comment by kevinkreiser** [comment]
i've been doing the following:

j = y as in english 'yellow'
oe = ö as in german 'göttin'
r = r as in spanish 'pero'
d = th as in english 'they'

people do tend to get annoyed with me though when i try to correct them from pronoucing it as, yord (rhymes with bored). so yeah... not sure what a proper course of action might be
