### ISSUE TITLE
Use 1/3rd arcsecond NED as well.

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/joerd#62]
Joerd pulls in the 1/9th arcsecond NED, but this doesn't have full coverage of the USA (yet?). The 1/3rd arcsecond has some issues around the coastline, but probably better than SRTM.

**Comment by nvkelso** [comment]
Background reading:

* http://nationalmap.gov/3DEP/3dep_prodserv.html

Map availability preview:

* http://viewer.nationalmap.gov/basic/?basemap=b1&category=ned,nedsrc&title=3DEP%20View

**Comment by nvkelso** [comment]
1/9 arc sec = 1 meter pixel size.
1/3 arc second = 10 meter pixel size.

**Comment by zerebubuth** [comment]
I think the 1m is a separate dataset. 1/9th arcsecond should be about 3m,
which is consistent with 1/3rd arcsecond being 10m?

**Comment by nvkelso** [comment]
Right you are:

```
Project-based

* 1-meter – This dataset was introduced in 2015 with limited coverage of the U.S., 
but will be expanding as new DEMs from 3DEP quality level 2 or better lidar data
are acquired. Horizontal coordinates are referenced to the Universal Transverse 
Mercator projection.

* 1/9 arc-second – This dataset covers about 25 percent of the conterminous U.S. 
and is produced from 3-meter or higher resolution DEMs acquired by the USGS prior 
to January 2015. Horizontal coordinates are referenced to geographic coordinates 
(longitude, latitude). The 1/9 arc-second dataset will no longer be updated with 
newly acquired DEMs; however, it will continue to be distributed.
```

**Comment by zerebubuth** [comment]
Tracking in #64.
